"""Synthetic training data generation for EconomyEncoder V1.

Two-step approach (per MODEL_SPEC.md):
    1. Structured economic scenarios with rule-based labels.
    2. Natural language variants generated by templating (no LLM needed for V1).

The label is ALWAYS derived from the economic rule, never from the
language variant. This ensures the model learns economics, not phrasing.
"""

from __future__ import annotations

from collections.abc import Mapping
import random
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class TrainingExample:
    """One (event, case, context, score) tuple for score training."""

    event_text: str
    case_text: str
    context_text: str
    score: float

    def to_serialized(self) -> str:
        return (
            "[CLS]\n"
            f"[EVENT] {self.event_text}\n"
            f"[CASE] {self.case_text}\n"
            f"[CONTEXT] {self.context_text}\n"
            "[SEP]"
        )


@dataclass(frozen=True, slots=True)
class ScenarioTemplate:
    """A structured economic scenario that produces a fixed label."""

    event_role: str
    case_role: str
    dependency: str
    magnitude: str
    expected_score: float
    event_templates: tuple[str, ...]
    case_templates: tuple[str, ...]
    context_templates: tuple[str, ...]


_TEMPLATES: tuple[ScenarioTemplate, ...] = (
    ScenarioTemplate(
        event_role="input_price_increase",
        case_role="consumer",
        dependency="high",
        magnitude="high",
        expected_score=-0.80,
        event_templates=(
            "Oil prices surged by 30 percent after supply disruptions",
            "Crude oil costs increased sharply in the global market",
            "Energy prices jumped following OPEC production cuts",
            "Fuel costs rose dramatically amid geopolitical tensions",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
            "type=airline name=[CASE_ENTITY]",
        ),
        context_templates=(
            "Fuel represents 35 percent of operating costs",
            "The company has minimal fuel hedging in place",
            "Kerosene is the largest single expense category",
            "No significant fuel hedging contracts exist",
        ),
    ),
    ScenarioTemplate(
        event_role="input_price_increase",
        case_role="producer",
        dependency="high",
        magnitude="high",
        expected_score=0.75,
        event_templates=(
            "Oil prices surged by 30 percent after supply disruptions",
            "Crude oil costs increased sharply in the global market",
            "Energy prices jumped following OPEC production cuts",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
            "type=oil_producer name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The company produces crude oil as its main product",
            "Revenue is directly tied to oil prices",
            "Higher oil prices increase profit margins",
        ),
    ),
    ScenarioTemplate(
        event_role="input_price_increase",
        case_role="neutral",
        dependency="low",
        magnitude="high",
        expected_score=0.0,
        event_templates=(
            "Oil prices surged by 30 percent after supply disruptions",
            "Crude oil costs increased sharply in the global market",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
            "type=software name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The company has no significant oil exposure",
            "Energy costs are negligible in the cost structure",
            "The business is not affected by commodity prices",
        ),
    ),
    ScenarioTemplate(
        event_role="customer_loss",
        case_role="supplier",
        dependency="high",
        magnitude="high",
        expected_score=-0.85,
        event_templates=(
            "A major customer terminated its contract immediately",
            "The largest client cancelled all future orders",
            "A key customer announced it will stop purchasing",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The customer accounted for 27 percent of revenue",
            "No replacement customer is currently known",
            "The contract has been terminated immediately",
        ),
    ),
    ScenarioTemplate(
        event_role="customer_loss",
        case_role="neutral",
        dependency="low",
        magnitude="medium",
        expected_score=-0.15,
        event_templates=(
            "A major customer terminated its contract immediately",
            "The largest client cancelled all future orders",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The customer accounted for 2 percent of revenue",
            "Replacement customers are readily available",
            "The revenue impact is minimal",
        ),
    ),
    ScenarioTemplate(
        event_role="export_restriction",
        case_role="affected_producer",
        dependency="high",
        magnitude="high",
        expected_score=-0.75,
        event_templates=(
            "China imposed export restrictions on semiconductor chips",
            "New export controls limit chip sales to key markets",
            "The government restricted exports of critical components",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
            "type=chip_manufacturer name=[CASE_ENTITY]",
        ),
        context_templates=(
            "32 percent of revenue comes from the restricted region",
            "Alternative markets are limited",
            "No domestic replacement demand exists",
        ),
    ),
    ScenarioTemplate(
        event_role="export_restriction",
        case_role="competitor",
        dependency="high",
        magnitude="high",
        expected_score=0.65,
        event_templates=(
            "China imposed export restrictions on semiconductor chips",
            "New export controls limit chip sales to key markets",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The company competes with restricted producers",
            "It can serve customers affected by the restrictions",
            "Market share is expected to increase",
        ),
    ),
    ScenarioTemplate(
        event_role="interest_rate_hike",
        case_role="bank",
        dependency="high",
        magnitude="medium",
        expected_score=0.45,
        event_templates=(
            "The central bank raised interest rates by 50 basis points",
            "Interest rates increased significantly",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
            "type=bank name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The company earns income from interest rate spreads",
            "Higher rates improve net interest margins",
        ),
    ),
    ScenarioTemplate(
        event_role="interest_rate_hike",
        case_role="real_estate",
        dependency="high",
        magnitude="medium",
        expected_score=-0.55,
        event_templates=(
            "The central bank raised interest rates by 50 basis points",
            "Interest rates increased significantly",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
            "type=real_estate name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The company carries high debt levels",
            "Financing costs are a major expense",
            "Higher rates reduce property valuations",
        ),
    ),
    ScenarioTemplate(
        event_role="demand_increase",
        case_role="producer",
        dependency="high",
        magnitude="medium",
        expected_score=0.60,
        event_templates=(
            "Demand for electric vehicles increased substantially",
            "Market demand for the product rose sharply",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The company produces components for electric vehicles",
            "Production capacity is available to meet demand",
        ),
    ),
)


def generate_training_examples(
    num_per_template: int = 100,
    seed: int = 42,
) -> list[TrainingExample]:
    """Generate synthetic training examples from rule-based templates.

    Each template produces num_per_template examples with random
    combinations of event/case/context phrasings. The score remains
    fixed per scenario.
    """
    rng = random.Random(seed)
    examples: list[TrainingExample] = []

    for template in _TEMPLATES:
        for _ in range(num_per_template):
            event = rng.choice(template.event_templates)
            case = rng.choice(template.case_templates)
            context_lines = list(template.context_templates)
            rng.shuffle(context_lines)
            num_context = rng.randint(1, min(3, len(context_lines)))
            context = ". ".join(context_lines[:num_context])

            examples.append(
                TrainingExample(
                    event_text=event,
                    case_text=case,
                    context_text=context,
                    score=template.expected_score,
                )
            )

    rng.shuffle(examples)
    return examples


def generate_counterexamples(num_groups: int = 50, seed: int = 42) -> list[TrainingExample]:
    """Generate grouped counterexamples: same event, different cases.

    This forces the model to use case and context, not just the event.
    """
    rng = random.Random(seed)
    examples: list[TrainingExample] = []

    grouped: dict[str, list[ScenarioTemplate]] = {}
    for template in _TEMPLATES:
        grouped.setdefault(template.event_role, []).append(template)

    for event_role, templates in grouped.items():
        if len(templates) < 2:
            continue
        for _ in range(num_groups):
            event = rng.choice(templates[0].event_templates)
            for template in templates:
                case = rng.choice(template.case_templates)
                context_lines = list(template.context_templates)
                rng.shuffle(context_lines)
                context = ". ".join(context_lines[: min(2, len(context_lines))])
                examples.append(
                    TrainingExample(
                        event_text=event,
                        case_text=case,
                        context_text=context,
                        score=template.expected_score,
                    )
                )

    rng.shuffle(examples)
    return examples


def generate_all(
    num_per_template: int = 100,
    num_counter_groups: int = 50,
    seed: int = 42,
) -> list[TrainingExample]:
    """Generate the full synthetic training dataset."""
    examples = generate_training_examples(num_per_template=num_per_template, seed=seed)
    counter = generate_counterexamples(num_groups=num_counter_groups, seed=seed + 1)
    return examples + counter


# ---------------------------------------------------------------------------
# Frozen-dataset loader — the bridge from dataset/* to training/*.
# ---------------------------------------------------------------------------

# Single source of truth for split roles lives in dataset.splits.  Importing
# the canonical tuples here keeps the loader and the metric in sync with the
# split contract without re-hard-coding the names.
from dataset.splits import (
    IID_EVAL_SPLITS,
    OOD_EVAL_SPLITS,
    SPLIT_NAMES,
)


class DatasetLoadError(ValueError):
    """Raised when a frozen dataset cannot be loaded for training."""


class FrozenDataset:
    """Loaded frozen dataset viewed through the training contract.

    ``train`` and ``validation`` are the labeled training splits.
    ``iid_test`` exposes the in-distribution test split(s) separately from the
    OOD splits, so the evaluation report never folds IID data into the OOD
    aggregate.  ``ood_splits`` holds only the genuinely out-of-distribution
    evaluation splits (entity / parameter / combination / hard / concept).

    Every exposed record is a :class:`dataset.schema.DatasetRecord` value and
    therefore carries a ``.score`` property compatible with the existing
    :class:`training.pipeline.ScoreDataset`.
    """

    __slots__ = (
        "dataset_dir",
        "manifest",
        "train",
        "validation",
        "iid_test",
        "ood_splits",
    )

    def __init__(
        self,
        dataset_dir: Path | str,
        *,
        train: tuple,
        validation: tuple,
        iid_test: tuple,
        ood_splits: Mapping[str, tuple],
        manifest: Mapping[str, object],
    ) -> None:
        self.dataset_dir = Path(dataset_dir)
        self.manifest = manifest
        self.train = train
        self.validation = validation
        self.iid_test = iid_test
        self.ood_splits = dict(ood_splits)

    @property
    def train_examples(self) -> tuple:
        """Alias for the train split, matching the existing pipeline naming."""

        return self.train

    @property
    def validation_examples(self) -> tuple:
        return self.validation

    def __len__(self) -> int:
        return len(self.train) + len(self.validation)

    def all_examples(self) -> tuple:
        """Return train + validation concatenated (for tokenizer training)."""

        return (*self.train, *self.validation)


def load_frozen_dataset_for_training(
    dataset_dir: Path | str,
    *,
    verify_hashes: bool = True,
) -> FrozenDataset:
    """Load a frozen dataset and expose the splits used by training.

    Thin wrapper around :func:`dataset.export.load_frozen_dataset` that
    separates labeled training/validation data, in-distribution test data, and
    the held-out OOD test splits, and keeps the manifest for reproducibility
    logging.
    """

    from dataset.export import load_frozen_dataset

    if isinstance(dataset_dir, str) and not dataset_dir.strip():
        raise DatasetLoadError("dataset_dir must be a non-empty path")
    root = Path(dataset_dir)
    if not root.exists():
        raise DatasetLoadError(f"frozen dataset not found: {root}")

    splits, manifest = load_frozen_dataset(root, verify_hashes=verify_hashes)

    missing = [name for name in ("train", "validation") if name not in splits]
    if missing:
        raise DatasetLoadError(
            f"dataset is missing required training splits: {missing}"
        )

    iid_test = tuple(
        records for name in IID_EVAL_SPLITS for records in splits.get(name, ())
    )
    # Keep the per-split identity so the evaluation report can still group by
    # split name; expose a flat list only where the caller wants convenience.
    ood_splits = {name: splits[name] for name in OOD_EVAL_SPLITS if name in splits}
    return FrozenDataset(
        dataset_dir=root,
        train=splits["train"],
        validation=splits["validation"],
        iid_test=iid_test,
        ood_splits=ood_splits,
        manifest=manifest,
    )
