"""Synthetic training data generation for EconomyEncoder V1.

Two-step approach (per MODEL_SPEC.md):
    1. Structured economic scenarios with rule-based labels.
    2. Natural language variants generated by templating (no LLM needed for V1).

The label is ALWAYS derived from the economic rule, never from the
language variant. This ensures the model learns economics, not phrasing.
"""

from __future__ import annotations

import random
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class TrainingExample:
    """One (event, case, context, score) tuple for score training."""

    event_text: str
    case_text: str
    context_text: str
    score: float

    def to_serialized(self) -> str:
        return (
            "[CLS]\n"
            f"[EVENT] {self.event_text}\n"
            f"[CASE] {self.case_text}\n"
            f"[CONTEXT] {self.context_text}\n"
            "[SEP]"
        )


@dataclass(frozen=True, slots=True)
class ScenarioTemplate:
    """A structured economic scenario that produces a fixed label."""

    event_role: str
    case_role: str
    dependency: str
    magnitude: str
    expected_score: float
    event_templates: tuple[str, ...]
    case_templates: tuple[str, ...]
    context_templates: tuple[str, ...]


_TEMPLATES: tuple[ScenarioTemplate, ...] = (
    ScenarioTemplate(
        event_role="input_price_increase",
        case_role="consumer",
        dependency="high",
        magnitude="high",
        expected_score=-0.80,
        event_templates=(
            "Oil prices surged by 30 percent after supply disruptions",
            "Crude oil costs increased sharply in the global market",
            "Energy prices jumped following OPEC production cuts",
            "Fuel costs rose dramatically amid geopolitical tensions",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
            "type=airline name=[CASE_ENTITY]",
        ),
        context_templates=(
            "Fuel represents 35 percent of operating costs",
            "The company has minimal fuel hedging in place",
            "Kerosene is the largest single expense category",
            "No significant fuel hedging contracts exist",
        ),
    ),
    ScenarioTemplate(
        event_role="input_price_increase",
        case_role="producer",
        dependency="high",
        magnitude="high",
        expected_score=0.75,
        event_templates=(
            "Oil prices surged by 30 percent after supply disruptions",
            "Crude oil costs increased sharply in the global market",
            "Energy prices jumped following OPEC production cuts",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
            "type=oil_producer name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The company produces crude oil as its main product",
            "Revenue is directly tied to oil prices",
            "Higher oil prices increase profit margins",
        ),
    ),
    ScenarioTemplate(
        event_role="input_price_increase",
        case_role="neutral",
        dependency="low",
        magnitude="high",
        expected_score=0.0,
        event_templates=(
            "Oil prices surged by 30 percent after supply disruptions",
            "Crude oil costs increased sharply in the global market",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
            "type=software name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The company has no significant oil exposure",
            "Energy costs are negligible in the cost structure",
            "The business is not affected by commodity prices",
        ),
    ),
    ScenarioTemplate(
        event_role="customer_loss",
        case_role="supplier",
        dependency="high",
        magnitude="high",
        expected_score=-0.85,
        event_templates=(
            "A major customer terminated its contract immediately",
            "The largest client cancelled all future orders",
            "A key customer announced it will stop purchasing",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The customer accounted for 27 percent of revenue",
            "No replacement customer is currently known",
            "The contract has been terminated immediately",
        ),
    ),
    ScenarioTemplate(
        event_role="customer_loss",
        case_role="neutral",
        dependency="low",
        magnitude="medium",
        expected_score=-0.15,
        event_templates=(
            "A major customer terminated its contract immediately",
            "The largest client cancelled all future orders",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The customer accounted for 2 percent of revenue",
            "Replacement customers are readily available",
            "The revenue impact is minimal",
        ),
    ),
    ScenarioTemplate(
        event_role="export_restriction",
        case_role="affected_producer",
        dependency="high",
        magnitude="high",
        expected_score=-0.75,
        event_templates=(
            "China imposed export restrictions on semiconductor chips",
            "New export controls limit chip sales to key markets",
            "The government restricted exports of critical components",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
            "type=chip_manufacturer name=[CASE_ENTITY]",
        ),
        context_templates=(
            "32 percent of revenue comes from the restricted region",
            "Alternative markets are limited",
            "No domestic replacement demand exists",
        ),
    ),
    ScenarioTemplate(
        event_role="export_restriction",
        case_role="competitor",
        dependency="high",
        magnitude="high",
        expected_score=0.65,
        event_templates=(
            "China imposed export restrictions on semiconductor chips",
            "New export controls limit chip sales to key markets",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The company competes with restricted producers",
            "It can serve customers affected by the restrictions",
            "Market share is expected to increase",
        ),
    ),
    ScenarioTemplate(
        event_role="interest_rate_hike",
        case_role="bank",
        dependency="high",
        magnitude="medium",
        expected_score=0.45,
        event_templates=(
            "The central bank raised interest rates by 50 basis points",
            "Interest rates increased significantly",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
            "type=bank name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The company earns income from interest rate spreads",
            "Higher rates improve net interest margins",
        ),
    ),
    ScenarioTemplate(
        event_role="interest_rate_hike",
        case_role="real_estate",
        dependency="high",
        magnitude="medium",
        expected_score=-0.55,
        event_templates=(
            "The central bank raised interest rates by 50 basis points",
            "Interest rates increased significantly",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
            "type=real_estate name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The company carries high debt levels",
            "Financing costs are a major expense",
            "Higher rates reduce property valuations",
        ),
    ),
    ScenarioTemplate(
        event_role="demand_increase",
        case_role="producer",
        dependency="high",
        magnitude="medium",
        expected_score=0.60,
        event_templates=(
            "Demand for electric vehicles increased substantially",
            "Market demand for the product rose sharply",
        ),
        case_templates=(
            "type=company name=[CASE_ENTITY]",
        ),
        context_templates=(
            "The company produces components for electric vehicles",
            "Production capacity is available to meet demand",
        ),
    ),
)


def generate_training_examples(
    num_per_template: int = 100,
    seed: int = 42,
) -> list[TrainingExample]:
    """Generate synthetic training examples from rule-based templates.

    Each template produces num_per_template examples with random
    combinations of event/case/context phrasings. The score remains
    fixed per scenario.
    """
    rng = random.Random(seed)
    examples: list[TrainingExample] = []

    for template in _TEMPLATES:
        for _ in range(num_per_template):
            event = rng.choice(template.event_templates)
            case = rng.choice(template.case_templates)
            context_lines = list(template.context_templates)
            rng.shuffle(context_lines)
            num_context = rng.randint(1, min(3, len(context_lines)))
            context = ". ".join(context_lines[:num_context])

            examples.append(
                TrainingExample(
                    event_text=event,
                    case_text=case,
                    context_text=context,
                    score=template.expected_score,
                )
            )

    rng.shuffle(examples)
    return examples


def generate_counterexamples(num_groups: int = 50, seed: int = 42) -> list[TrainingExample]:
    """Generate grouped counterexamples: same event, different cases.

    This forces the model to use case and context, not just the event.
    """
    rng = random.Random(seed)
    examples: list[TrainingExample] = []

    grouped: dict[str, list[ScenarioTemplate]] = {}
    for template in _TEMPLATES:
        grouped.setdefault(template.event_role, []).append(template)

    for event_role, templates in grouped.items():
        if len(templates) < 2:
            continue
        for _ in range(num_groups):
            event = rng.choice(templates[0].event_templates)
            for template in templates:
                case = rng.choice(template.case_templates)
                context_lines = list(template.context_templates)
                rng.shuffle(context_lines)
                context = ". ".join(context_lines[: min(2, len(context_lines))])
                examples.append(
                    TrainingExample(
                        event_text=event,
                        case_text=case,
                        context_text=context,
                        score=template.expected_score,
                    )
                )

    rng.shuffle(examples)
    return examples


def generate_all(
    num_per_template: int = 100,
    num_counter_groups: int = 50,
    seed: int = 42,
) -> list[TrainingExample]:
    """Generate the full synthetic training dataset."""
    examples = generate_training_examples(num_per_template=num_per_template, seed=seed)
    counter = generate_counterexamples(num_groups=num_counter_groups, seed=seed + 1)
    return examples + counter